// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnVC8VbdAGDo-KIG_2chjBPLQzoh_WKQ',
    appId: '1:1097369011286:web:d107dedd12eb18eef4a7f7',
    messagingSenderId: '1097369011286',
    projectId: 'fir-learn-f00b9',
    authDomain: 'fir-learn-f00b9.firebaseapp.com',
    storageBucket: 'fir-learn-f00b9.appspot.com',
    measurementId: 'G-XQ82DZGF9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMDDp2OehyIj5jkyuMX3iv5741BlBX_4',
    appId: '1:1097369011286:android:c7208d4787f2ac1df4a7f7',
    messagingSenderId: '1097369011286',
    projectId: 'fir-learn-f00b9',
    storageBucket: 'fir-learn-f00b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgmntnfU0ofhubc1HX_XISQVw_-4jxgg',
    appId: '1:1097369011286:ios:0a39cc18e0bbc886f4a7f7',
    messagingSenderId: '1097369011286',
    projectId: 'fir-learn-f00b9',
    storageBucket: 'fir-learn-f00b9.appspot.com',
    iosBundleId: 'com.example.firebaseFeature',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgmntnfU0ofhubc1HX_XISQVw_-4jxgg',
    appId: '1:1097369011286:ios:0a39cc18e0bbc886f4a7f7',
    messagingSenderId: '1097369011286',
    projectId: 'fir-learn-f00b9',
    storageBucket: 'fir-learn-f00b9.appspot.com',
    iosBundleId: 'com.example.firebaseFeature',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpnVC8VbdAGDo-KIG_2chjBPLQzoh_WKQ',
    appId: '1:1097369011286:web:8243042384ff60def4a7f7',
    messagingSenderId: '1097369011286',
    projectId: 'fir-learn-f00b9',
    authDomain: 'fir-learn-f00b9.firebaseapp.com',
    storageBucket: 'fir-learn-f00b9.appspot.com',
    measurementId: 'G-8TQZ9P8M9S',
  );
}
