// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTwYsoDPzu9axdD2LvXGABKBKDN9jWfRU',
    appId: '1:428831322692:android:e9504c5a3785b7bd828211',
    messagingSenderId: '428831322692',
    projectId: 'fir-feature-49943',
    storageBucket: 'fir-feature-49943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYCS9qLs7xk-yZywCtI9yWfsYpnuQilo',
    appId: '1:428831322692:ios:849ce552bc1bb1d5828211',
    messagingSenderId: '428831322692',
    projectId: 'fir-feature-49943',
    storageBucket: 'fir-feature-49943.appspot.com',
    androidClientId: '428831322692-u092cmlfkbo9diqqee549ka41elo6mp4.apps.googleusercontent.com',
    iosClientId: '428831322692-or9h6l2lf0vq67qbbs1ekd333m2pmq6b.apps.googleusercontent.com',
    iosBundleId: 'com.beltei.learning',
  );

}